baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: jarossnd.mode
paginate: 5
theme: jarossndmode



menu:
    main:
        - name: Contact
          url: /contact/
          weight: 35
        - name: Articles
          url: /articles/
          weight: 30
        - name: Projects
          url: /projects/
          weight: 20
       # - name: Experience
        #  url: /experience/
        #  weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Jason Ross


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Jason Ross
        description: |

          Hello, I am Jason.
           I am a web developer. 
        

          I'm glad you're here!
        imageUrl: "/images/profile.png"
        imageTitle: A picture of Jason Ross
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/jarossnd"
        - name: linkedin
          url: "https://www.linkedin.com/in/jason-ross-msft"
        - name: twitter
          url: "https://twitter.com/jarossnd"
        - name: buymeacoffee
          url: "https://ko-fi.com/jaross"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

